services:
  - type: web
    name: hanuko-discord-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python hanuko_bot.py
    envVars:
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: PORT
        value: 8080
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_PORT
        value: 5432
    plan: free 