services:
  - type: web
    name: hanuko-discord-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python hanuko_bot.py
    envVars:
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: PORT
        value: 8080
    plan: free 